{
 "title": "containerd",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": {
     "query": "label_values(process_resident_memory_bytes{job=\"monitoring/containerd-monitor\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Containerd Build Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Containerd Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "containerd_build_info_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Containerd Commit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 11, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "containerd_build_info_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  { "title": "Containerd CRI 请求时长", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "CRI List Container 耗时分布",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(containerd_cri_container_list_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(containerd_cri_container_list_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(containerd_cri_container_list_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(containerd_cri_container_list_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "CRI 镜像拉取次数",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "sum(containerd_cri_image_pulls_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}) by (status) "
    }
   ]
  },
  {
   "title": "CRI Remove Container 耗时分布",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(containerd_cri_container_remove_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(containerd_cri_container_remove_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(containerd_cri_container_remove_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(containerd_cri_container_remove_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "CRI Stop Container 耗时分布",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 17, "y": 5 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(containerd_cri_container_stop_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(containerd_cri_container_stop_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(containerd_cri_container_stop_seconds_bucket[5m])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(containerd_cri_container_stop_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  { "title": "Containerd Process Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "process_virtual_memory_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "process memory deriv",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(process_resident_memory_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - resident"
    },
    {
     "expr": "deriv(process_virtual_memory_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 15, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[30s])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{namespace=~\"^($namespace)$\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "go memstats deriv",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "deriv(go_memstats_alloc_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - alloc rate"
    },
    {
     "expr": "deriv(go_memstats_stack_inuse_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - stack inuse"
    },
    {
     "expr": "deriv(go_memstats_heap_inuse_bytes{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}} - heap inuse"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "open fds deriv",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "deriv(process_open_fds{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{namespace=~\"monitoring\",pod=~\"^($pod)$\"}",
     "legendFormat": "{{pod}}: {{quantile}}"
    }
   ]
  },
  { "title": "Containerd GRPC Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "grpc_server_handle_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "grpc_server_handled_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "Containerd GRPC 请求 耗时分布",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(grpc_server_handling_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_server_handling_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_server_handling_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p99.9"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(grpc_server_handling_seconds_bucket{namespace=~\"monitoring\",pod=~\"^($pod)$\"}[5m])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "grpc_server_msg_received_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "grpc_server_msg_received_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "grpc_server_started_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "grpc_server_started_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  },
  {
   "title": "grpc_server_msg_sent_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "grpc_server_msg_sent_total{namespace=~\"monitoring\",pod=~\"^($pod)$\"}"
    }
   ]
  }
 ]
}